### PR TITLE
Swift 4.1: Utilize synthesized Equatable impl

### PR DESCRIPTION
**Pull request by ikesyo**

### CODE REVIEW

**Comment by mdiep** [comment]
Are we ready to require this?

If we use it for Carthage, then Carthage will only build on Xcode 9.3 and thus only build on macOS 10.13. 😕

**Comment by ikesyo** [comment]
Good point, so should we still support Xcode 9.2/Swift 4.0 for several months, maybe until Swift 4.2?

**Comment by mdiep** [comment]
Probably—or even until 10.14 is out. 😞

**Comment by mdiep** [comment]
Unfortunately, there's a CI failure. 😞

**Comment by ikesyo** [comment]
Yes, that should be addressed by #127.

**Comment by mdiep** [comment]
Sorry. Hadn't made it to that PR yet. 😅

**Pull request merged**
