### PR TITLE
Expose a public initializer to NoOptions so that tests can be written for commands that take NoOptions

### PR DESCRIPTION
**Pull request by younata**
Why was this not exposed earlier?

### CODE REVIEW

**Comment by younata** [comment]
Probably because no one ever actually wrote tests that would drive this need out... because apparently, it's like taking crazy pills to actually test your stuff.

**Comment by ikesyo** [comment]
Why not just call `NoOptions<Error>.evaluate(.Usage)`?

**Comment by younata** [comment]
Because `NoOptions<Error>()` is infinitely more readable.

**Comment by mdiep** [comment]
This seems fine. :+1:

> Why was this not exposed earlier?

I think it just wasn't obvious that it would be useful.

**Pull request merged**
