### PR TITLE
Generate error on unrecognized arguments

### PR DESCRIPTION
**Pull request by norio-nomura**
It will alert users to the typo of arguments.

e.g.
```sh
% carthage checkout --use-submodule
*** Checking out xcconfigs at "ec5753493605deed7358dec5f9260f503d3ed650"

Unknown arguments are ignored: --use-submodule
%
```

### CODE REVIEW

**Comment by NachoSoto** [comment]
It seems weird to rely on the object lifetime to print this error.

**Comment by mdiep** [comment]
> It seems weird to rely on the object lifetime to print this error

I agree. It looks like this should become a `CommandantError` that's returned at some stage in the process.

**Comment by norio-nomura** [comment]
Thank you for reviews.

> It seems weird to rely on the object lifetime to print this error.

Sorry, my bad code. I rewrote it.

> It looks like this should become a CommandantError that's returned at some stage in the process.

Producing some error before running commands will need to separate evaluating options on each commands.
That will be breaking changes and I can't determine that it will be reasonable.

**Comment by mdiep** [comment]
`CommandRegistry.main()` should print an error and exit if there's an used option—like it does for unrecognized commands. It's okay if that's a breaking change because it's a behavior we want (#2).

**Comment by norio-nomura** [comment]
@mdiep Thanks.
I added `OptionsType.evaluateAndCheckUnknownArguments()` for calling on each commands.
e.g.
```diff
 	public func run(mode: CommandMode) -> Result<(), CommandantError<ClientError>> {
-		return HelpOptions<ClientError>.evaluate(mode)
+		return HelpOptions<ClientError>.evaluateAndCheckUnknownArguments(mode)
```

**Comment by norio-nomura** [comment]
I think I should change "unknown options" to "unrecognized arguments".

**Comment by mdiep** [comment]
@Carthage/carthage Anyone have thoughts on this approach? I really don't like the design of Commandant, which makes it hard to judge this.

**Comment by norio-nomura** [comment]
Thanks @ikesyo for moving forward. :bow:

**Comment by NachoSoto** [comment]
Sorry for the delay.
This is much better!

**Comment by norio-nomura** [comment]
No problem! Thank you all. :pray:

**Pull request closed without merging**
