### PR TITLE
add support for Swift Package Manager

### PR DESCRIPTION
**Pull request by jpsim**
Pointing to `jpsim/Result` for now because there's no tag of `antitypical/Result` containing `Package.swift`.

Due to apple/swift-package-manager#16, I had to rename `CommandantTests` to `Tests`.

### CODE REVIEW

**Comment by mdiep** [comment]
> Pointing to jpsim/Result for now because there's no tag of antitypical/Result containing Package.swift.

Could you open a pull request on Result to add `Package.swift`? I'd prefer to have support there before we add support here.

**Comment by jpsim** [comment]
`antitypical/Result` already has a `Package.swift` but doesn't have a tag with it, which SPM needs. We could point this there, but it wouldn't work until a new release is made.

**Comment by mdiep** [comment]
I just created a new release for antitypical/Result that includes the `Package.swift`. If you update this PR, we can merge it. It'd also be nice if we could test the linux build on CI, but I'm not sure what the state of that is.

**Comment by jpsim** [comment]
This is pointing to `antitypical/Result` now. Although Commandant Linux support is blocked on antitypical/Result#135, so I haven't included anything Linux-specific in this PR.

**Comment by jpsim** [comment]
I'll be tracking the Linux-specific Commandant changes here: https://github.com/jpsim/Commandant/compare/spm...linux

**Comment by mdiep** [comment]
Looks great! Thanks! :sparkles:

**Comment by jpsim** [comment]
It'd be great to cut a new release of Commandant with this change, so we can stop pointing other SPM projects to unofficial forks :smile: .

**Comment by mdiep** [comment]
I'll try to do that tonight or in the morning. :+1:

**Comment by jpsim** [comment]
Thanks :sparkles:

**Comment by mdiep** [comment]
I just released 0.8.3. :sparkles:

**Comment by jpsim** [comment]
Fantastic, thanks!

**Pull request merged**
