### PR TITLE
Restore Travis

### PR DESCRIPTION
**Pull request by ikesyo**

### CODE REVIEW

**Comment by jspahrsummers** [comment]
Thanks! Looks like this has exposed a build failure, though. :flushed:

**Comment by ikesyo** [comment]
Oh, I'll check it. :disappointed:

**Comment by ikesyo** [comment]
I've done with checking out `Box` and `Result` missed in #25. :sweat_smile:

**Comment by jspahrsummers** [comment]
Thanks! Sorry about that.

**Pull request merged**
