### PR TITLE
Update Quick 2.0.0 Nimble 8.0.0

### PR DESCRIPTION
**Pull request by doozMen**
I also ignored the Xcode project file. Maybe this is not needed and then I can remove it.

### CODE REVIEW

**Comment by norio-nomura** [comment]
> I also ignored the Xcode project file. Maybe this is not needed and then I can remove it.

AFAIK, SourceKitten and SwiftLint are still configured on the assumption that Commandant has Xcode project yet.
@jpsim @marcelofabri Can we drop Xcode project on SwiftLint and SourceKitten?

**Comment by jpsim** [comment]
Sorry I must have missed a conversation somewhere, why is the Xcode project being removed? Seems like a useful thing to keep?

**Comment by norio-nomura** [comment]
> Seems like a useful thing to keep?

I thought so.
However, I knew that the Xcode project had already been deleted in Carthage, and I was concerned about whether there is a motivation to positively delete the Xcode project from repository. 🤔

**Comment by norio-nomura** [comment]
I opened #142 that includes this.

**Comment by doozMen** [comment]
@norio-nomura  and @ikesyo  I think you should not merge this branch. I have some problems with indeed AFAIK, SourceKitten and SwiftLint not yet updated to quick and nimble new breaking releases. Also removing the Xcode project seams harsh. It is more a discussion point. I used to be against it but now that the swift package manager actually generates a useful Xcode project every time (in my latest experience) I think it is dangerous to leave it as you will be tempted to change stuff in it. Maybe it could be an option, for legacy support, to move Xcode project to a subfolder as swift package manager depends on it to be in tech root folder?

**Comment by doozMen** [comment]
Will you close this PR or should I do this? Thanks for the good feedback!

**Comment by norio-nomura** [comment]
@doozMen: Sorry for confusion. 🙇 
I rebased #142 to your changes and will continue on that.
Thanks for contribution!

**Pull request closed without merging**
