### PR TITLE
Introduce `Argument` type which can handle an argument list

### PR DESCRIPTION
**Pull request by ikesyo**
This is needed at https://github.com/Carthage/Carthage/pull/972#issuecomment-164314514.

- A positional argument is represented as `Argument` now.
- If `Argument` is tied to a property of `Array<ArgumentType>` type, that consumes the rest of positional arguments entirely.
- `Option.key` is non-optional now.

### CODE REVIEW

**Comment by mdiep** [comment]
This branch has conflicts that must be resolved.

:weary:

**Comment by mdiep** [comment]
Looks good to me! :+1: :sparkles:

**Comment by ikesyo** [comment]
Resolved the conflicts! :smiley:

**Comment by mdiep** [comment]
:tada:

**Pull request merged**
