### PR TITLE
⬆️ Update dev dependencies

### PR DESCRIPTION
**Pull request by phatblat**
- xcconfigs (1.0)
- Quick (2.2.1)
- Nimble (8.1.1)

### CODE REVIEW

**Comment by tmspzz** [comment]
There seems to be a problem in one step on CI. Can you take a look at that?

**Comment by phatblat** [comment]
> The command "pod repo update master" exited with 1.

This command is probably obsolete now with the CocoaPods trunk repo being the default. I'll fix the travis script tonight.

**Comment by phatblat** [comment]
Fixed now. I got the same error when I switched the command to update the `trunk` repo, so I changed it to do `pod setup` which installs the `trunk repo`

**Comment by tmspzz** [comment]
🙇‍♂️ thanks for the PR!

**Pull request merged**
