### PR TITLE
Release 0.17.0

### PR DESCRIPTION
**Pull request by giginet**
#146 

[Remove Result dependency by daltonclaybrook · Pull Request #146 · Carthage/Commandant](https://github.com/Carthage/Commandant/pull/146)

Bumped up version to 0.17.0

### CODE REVIEW

**Comment by giginet** [comment]
#151 should be merged before this

**Comment by giginet** [comment]
Thanks!

**Comment by giginet** [comment]
@mdiep I can create GitHub release. But I don't have permission to update pod trunk. 
Could you release newer version?

**Comment by mdiep** [comment]
I don't have CocoaPods permissions either. I think @ikesyo will need to do that.

**Comment by phatblat** [comment]
Created [0.17.0](https://github.com/Carthage/Commandant/releases/tag/0.17.0) release (since CocoaPods needs the tag in order to publish).

**Comment by phatblat** [comment]
[0.17.0](https://cocoapods.org/pods/Commandant) has been pushed to CocoaPods trunk now.

@giginet I've added you as an owner using the email showing on your GitHub account. @mdiep your GitHub email isn't showing up as being registered with an account on trunk.

```
$ pod trunk add-owner Commandant matt@...
[!] No owner found with the specified email address.
```

**Pull request merged**
